apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-init-sql
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS "Forecasts" (
        "Id" SERIAL PRIMARY KEY,
        "Summary" TEXT,
        "TemperatureC" INTEGER,
        "Date" TIMESTAMP NOT NULL DEFAULT NOW()
    );
