apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aurora-db-secret
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "weatherapp/db-credentials"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: db-credentials
      type: Opaque
      data:
        - objectName: "master_username"
          key: master_username
        - objectName: "master_password"
          key: master_password
        - objectName: "writer_endpoint"
          key: writer_endpoint
        - objectName: "reader_endpoint"
          key: reader_endpoint
