name: weather-app

image:
  repository: repository/weather-app
  tag: latest

domain: weather.kiu.com
replicaCount: 2

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

db:
  host: your-db-host.rds.amazonaws.com
  name: weatherdb
  user: admin
  secretName: db-password
  secretKey: master_password

tls:
  issuer: letsencrypt-prod

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
